### ISSUE TITLE
em++ error

### ISSUE THREAD

**Issue by gbtami** [ianfab/stockfish.wasm#2]
I try to compile with latest emsdk, but get this
`em++: error: Passing any of -msse, -msse2, -msse3, -mssse3, -msse4.1, -msse4.2, -mavx flags also requires passing -msimd128!`

If I add `-msimd128` to the make file it compiles Ok (except some warnings), but Chromium is not happy:
![https://i.imgur.com/QdwrcxL.png](https://i.imgur.com/QdwrcxL.png)

**Comment by notruck** [comment]
I also ran into the same problems as gbtami when using the default Makefile. `(em++ error, had to pass -msimd128 to compile "successfully," and then the Chromium console showing the same errors as in his screenshot)`

However, it will all compile OK if `popcnt=no` is set in the Makefile here:

https://github.com/ianfab/stockfish.wasm/blob/master/src/Makefile#L150 

The resultant .js/.wasm files will run alright on Chromium, although rather slow from lacking the SSE/SIMD :( 

but at least it works, and this option is "error-free" for me.

**Comment by notruck** [comment]
For my next try, I compiled aiming for the equivalent of `ARCH=x86-64` (still `popcnt = no`, but with `prefetch = yes` and `sse = yes`). 

This time I had to pass the `-msimd128` flag. It compiles, and runs, but Chromium seemed less happy with it. Some warnings were issued. 

Thie good news is, this binary runs 15-20% faster on x86-64, although I don't know whether this (or even the one before) will run on 64-bit ARM, which is probably also a future goal with WASM?

Anyway, I followed Chromium's prompts and enabled a few extra/experimental `chrome://flags` and also set  `ASSERTIONS=1` in the Makefile's EMFLAGS, 

`make -j build ARCH=wasm EXTRACXXFLAGS='-msimd128' EXTRALDFLAGS='-msimd128'` compiled with a few warnings.

**Comment by ianfab** [comment]
When I last tested it it worked for me and I have not done any code changes since then, so I will need to see if I will be able to reproduce it. However, in any case it probably makes sense to set up CI for the WASM build to at least make sure that it compiles fine under well-defined conditions. The makefile originates from the WASM port for lichess, so I assume it should be fine, but maybe the error is related to changes in Fairy-SF.

**Comment by gbtami** [comment]
It worked for me without any change before also.
I think the "problem" is latest emsdk because I updated it now as described in https://emscripten.org/docs/getting_started/downloads.html
I can imagine that they enhanced/developed em++ further, but this hurts us badly here.

**Comment by ianfab** [comment]
Ah ok, thanks, I assumed it was never working for you.

**Comment by notruck** [comment]
If you still have the older versions of emscripten set up and working, probably a good idea to hold onto that as is, and only attempt to update to their latest version separately. There's a possibility that their latest changes may be hurting both compatibility and speed :(

**Comment by gbtami** [comment]
Thx! Fortunately you can install older version, so after reading https://github.com/emscripten-core/emscripten/blob/master/ChangeLog.md I tried
`./emsdk install 1.39.16`
`./emsdk activate 1.39.16`

Noticed several warnings like
```
root:WARNING: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271
clang-11: warning: argument unused during compilation: '-msse3' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-mpopcnt' [-Wunused-command-line-argument]
```
but it worked!

**Comment by ianfab** [comment]
Due to the switch to the new `nnue` branch with a more recent emscripten version, this is now obsolete.
