### ISSUE TITLE
Merge Fairy-Stockfish updates

### ISSUE THREAD

**Issue by gbtami** [ianfab/stockfish.wasm#5]
@ianfab  may i ask you to merge latest Fairy to wasm port again, please?

**Comment by ianfab** [comment]
Thanks for the reminder, although I did not really forget, it just takes longer because there are merge conflicts and I will also need to merge upstream stockfish.wasm, but I am a bit busy now. But I promise I will get back to it.

**Comment by ianfab** [comment]
The old WASM version will no longer be maintained and replaced by the new implementation on `nnue` branch.
