### ISSUE TITLE
Provide npm package

### ISSUE THREAD

**Issue by gbtami** [ianfab/stockfish.wasm#6]
It would be nice to have packages similar to https://github.com/niklasf/stockfish.wasm
Then we can remove binaries from pychess git.

**Comment by TheYoBots** [comment]
Yes it could even be used on lishogi instead of adding binaries. Hope this get published onto npm soon.

**Comment by gbtami** [comment]
Seems a modified https://github.com/ianfab/stockfish.wasm/blob/nnue/src/emscripten/public/package.json can be used for this task (npm publish).

**Comment by ianfab** [comment]
I added a publishing step to the CI workflow which is only executed on tag creation. This now created a first package version at https://www.npmjs.com/package/fairy-stockfish-nnue.wasm.

**Comment by gbtami** [comment]
Works like charm. Thx!
